import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
} from "typeorm";

@Entity("conversation_memories")
export class ConversationMemoryEntity {
  @PrimaryGeneratedColumn("uuid")
  id: string;

  @Column()
  userId: string;

  /** Distilled memory text generated by the LLM */
  @Column({ type: "text" })
  content: string;

  /** Which conversation originated this memory */
  @Column({ nullable: true })
  sourceConversationId: string;

  @CreateDateColumn()
  createdAt: Date;
}
